### ISSUE TITLE
目前是什么阶段？

### ISSUE THREAD

**Issue by helloyan** [cloversuite/CloverQ#1]

**Comment by cloversuite** [comment]
Hello helloyan this project is fully functional. I am currently developing a simple frontend based on Elastiksearch and Kibana, and another based on SignalR, Asp.Net MVC and Angular 5 to show metrics in real time.
I do not have a precise date for the release of these modules.
If you are interested in using this project, I would like you to tell me about it.
Best regards.
Alejo.
